### ISSUE TITLE
[BUG] At Developers page, devs order doesn't change in reload

### ISSUE THREAD

**Issue by iguoliveira** [monkey-developers/monkeydevs.org#7]
### Current Behaviour
When the page is refreshed, devs positions change, but they remain in the same order.

### Expected Behaviour
When the page is refreshed, devs position and order must be random

**Comment by abehidek** [comment]
probably some bizarre issue regarding `React.useMemo()` hook

**Comment by viktormarinho** [comment]
Actually i believe the problem lies in astro rendering the developers order at build time.
In devmode everything is ok when refreshing the page, but in prod the order always stays the same. The **positions** change, but the people order stays static.

**Comment by abehidek** [comment]
Tested here and the devs order do not change even accessing through different computers/networks

Doesn't make sense tho, upon inspecting code we see that CommitGraphDevs.tsx component are supposed to run on client because of `client:load` directive is present in `src/pages/devs.astro`.

**Comment by abehidek** [comment]
I really don't know if the bugs lies here, but upon seeing [docs](https://docs.astro.build/en/core-concepts/framework-components/#available-hydration-directives), it seems that the directive makes a component hydrated by the server on request, which makes the component rendered twice (server-side and client-side)

And because the page was statically generated means that some kind of conflict happens between the server rendered component state and client side rendered component state

**Comment by abehidek** [comment]
fixed: https://github.com/monkey-developers/monkeydevs.org/commit/d38357f18dfd7dee47573d60832ff8c7829941fd

[source](https://docs.astro.build/en/reference/directives-reference/#clientonly)

**Comment by TayAntony** [comment]
Qq isso? Tem que comentar oq?
